package vcom.sso.vo;


/**
 * SysArea generated by MyEclipse Persistence Tools
 */

public class SysArea implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 874526751798046491L;

	// Fields

	private String areaId;

	private String areaCode;

	private String fid;

	private String areaname;

	private String fullname;

	private String levelFlg;
	
	private String isNode;
	
	private String flag;
	


	// Constructors


	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getIsNode() {
		return isNode;
	}

	public void setIsNode(String isNode) {
		this.isNode = isNode;
	}

	/** default constructor */
	public SysArea()
	{
	}

	/** minimal constructor */
	public SysArea(String fid, String areaname, String levelFlg)
	{
		this.fid = fid;
		this.areaname = areaname;
		this.levelFlg = levelFlg;
	}

	/** full constructor */
	public SysArea(String areaCode, String fid, String areaname,
			String fullname, String levelFlg)
	{
		this.areaCode = areaCode;
		this.fid = fid;
		this.areaname = areaname;
		this.fullname = fullname;
		this.levelFlg = levelFlg;
	}

	// Property accessors

	public String getAreaId()
	{
		return this.areaId;
	}

	public void setAreaId(String areaId)
	{
		this.areaId = areaId;
	}

	public String getAreaCode()
	{
		return this.areaCode;
	}

	public void setAreaCode(String areaCode)
	{
		this.areaCode = areaCode;
	}

	public String getFid()
	{
		return this.fid;
	}

	public void setFid(String fid)
	{
		this.fid = fid;
	}

	public String getAreaname()
	{
		return this.areaname;
	}

	public void setAreaname(String areaname)
	{
		this.areaname = areaname;
	}

	public String getFullname()
	{
		return this.fullname;
	}

	public void setFullname(String fullname)
	{
		this.fullname = fullname;
	}

	public String getLevelFlg()
	{
		return this.levelFlg;
	}

	public void setLevelFlg(String levelFlg)
	{
		this.levelFlg = levelFlg;
	}
	
	public int hashCode()
	{
		return this.getAreaId().hashCode();
	}
	public boolean equals(Object o)
	{
		if(o==null) return false;
		if(this==o) return true;
		if(this.getAreaId()==null || !(o instanceof SysArea))
			return false;
		SysArea area=(SysArea)o;
		return this.getAreaId().equals(area.getAreaId());
	}
}